### ISSUE TITLE
Using this project with PLY files

### ISSUE THREAD

**Issue by Naor92** [daveredrum/Pointnet2.ScanNet#1]
Hi @daveredrum ,

Sorry to bother you, trying to use this project to segment some .ply files I have. Was wondering if you can spare some more details on how the project works. I can't seem to find a way to download the original dataset, can we skip the training portion if we download the pre-trained models you provided? And if so, can we segment our own PLY files using the trained models?

**Comment by daveredrum** [comment]
Yes, you can test the pre-trained models on your own data, but in this case, you should write your own preprocessing+dataloader for the .ply files.

As for downloading the ScanNet dataset, please refer to the documentation in [ScanNet Benchmark](http://www.scan-net.org/), or use the pre-processed data [here](https://github.com/charlesq34/pointnet2/tree/master/scannet)

**Comment by Naor92** [comment]
Appreciate the response Dave! One more quick question for you, when I try to train the model I get an import error that no module named PointNet2ScanNetDataset can be found. Is this meant to be taken from PointNet++'s scannet_dataset.py file and edited accordingly?

**Comment by daveredrum** [comment]
Could you elaborate a bit more so that I can reproduce the error?

**Comment by Naor92** [comment]
Sure. When running the train.py file, it calls the eval.py file, which in turn tries to call the following on line 8:

from PointNet2ScanNetDataset import ScannetDatasetWholeScene, collate_wholescene

Problem is I don't see the PointNet2ScanNetData set file anywhere. Possibly missing somehow or am I missing something?

**Comment by daveredrum** [comment]
Then it should be a legacy issue from an older version. I've fixed that and the code should run perfectly. Please pull the new version :)

**Comment by Naor92** [comment]
Hi Dave, thanks again for the quick responses - very helpful! I am now just waiting on the database from the PointNet owners and then I will give the new code a test.

**Comment by Naor92** [comment]
Hi again Dave, the dataset was too large for me to download so I opted to download the preprocessed data as you suggested from the PointNet++ code. It gave me a test pickle file and a train pickle file. However when I try to run the train.py script I get the following does not exist error:

../Pointnet2.ScanNet/preprocessing/scannet_scenes/scene0191_00.npy'

I guess I'm a bit confused on what to do with this data since I wasn't able to download the original dataset to run the preprocessing code. How do I get the scene npy files from the preprocessed data so that I can train/evaluate? 

*And again, thank you for all the help!!*

**Comment by daveredrum** [comment]
When I started with this project, I assumed that ScanNet is already accessible locally. In your case, I strongly suggest you to modify the [dataloader](https://github.com/daveredrum/Pointnet2.ScanNet/blob/master/lib/dataset.py) to adapt to your need. If I didn't misunderstand anything there, the pickle file you've downloaded should contain all pre-processed point clouds as numpy arrays.
