### ISSUE TITLE
two small bugs I found

### ISSUE THREAD

**Issue by antmillar** [daveredrum/Pointnet2.ScanNet#4]
thanks for the great repo

couple of things I had to change to make it work locally

https://github.com/daveredrum/Pointnet2.ScanNet/blob/master/preprocessing/collect_scannet_scenes.py

line 63-64, repeated line

https://github.com/daveredrum/Pointnet2.ScanNet/blob/master/preprocessing/scannet_util.py

9)  lines = [line.rstrip() for line in open('scannetv2-labels.combined.tsv')]

this function is later called in a higher level directory (collect_scannet_scenes fn) so I had to amend the URL

also I had to add "is_msg = False" to the model load in both visualize and eval.py, otherwise I got layer size mismatch errors when trying to run those

**Comment by daveredrum** [comment]
Hey @antmillar, thanks a lot for pointing that out! could you please elaborate more about the URL issue?

**Comment by antmillar** [comment]
hey no worries, thanks a lot for the repo! I've been building a web app to segment architectural scenes with it

I don't recall exactly, but it looks like I've changed the line to 

`    lines = [line.rstrip() for line in open('preprocessing/scannetv2-labels.combined.tsv')]`

I guess it's because on the readme you said to run python "preprocessing/collect_scannet_scenes.py" from the base directory so I think I got an error 

---

Also fwiw I removed these lines from https://github.com/daveredrum/Pointnet2.ScanNet/blob/master/lib/dataset.py

```
    140            if sum(mask)/float(len(mask))<0.01:
    141              continue
```
as I couldn't understand what it was doing

**Comment by daveredrum** [comment]
Should be fixed now.
