### ISSUE TITLE
I can't test the pretrained model

### ISSUE THREAD

**Issue by rjose97** [daveredrum/Pointnet2.ScanNet#7]
Hello @daveredrum 
First say thank you for your work.

I was trying to test the pretrained models created. And for some reason they don't charge me. I have tried both msg and ssg. And none of them give me results.
I don't know why it happens.

I also wanted to ask you if it is possible to use your own ply's.

Thanks in advance. Regards.

![Captura de pantalla de 2020-08-19 08-27-57](https://user-images.githubusercontent.com/54666078/90599900-f57bf480-e1f5-11ea-8601-56d258b97fca.png)

**Comment by daveredrum** [comment]
Should be fixed now.
