### ISSUE TITLE
Data Chunks Generation

### ISSUE THREAD

**Issue by Ze-Yang** [daveredrum/Pointnet2.ScanNet#9]
Hi, I find it hard to understand what is going on with the data chunks generation process in the file below. https://github.com/daveredrum/Pointnet2.ScanNet/blob/f4adc43779aaaefd6138d37183a94185d0718865/lib/dataset.py#L219-L240

1. What is line 236 meant for?
2. How should the [31, 31, 62] in line 235 be chosen?
3. What are the criteria "np.sum(cur_semantic_seg>0)/len(cur_semantic_seg)>=0.7" and "len(vidx)/31.0/31.0/62.0>=0.02" in line 237 mean?

Thanks.

**Comment by daveredrum** [comment]
Hi @Ze-Yang,

1. This line is for hashing the voxel coordinates after voxelizing the point cloud;
2. The points sampled in the 1.5m by 1.5m by 3m cubes are voxelized with resulotion 2cm;
3. We check the occupancy rate of the voxels in the cube and the object surfaces. More details in Sec. B.4 in the original [paper](https://arxiv.org/pdf/1706.02413.pdf).

Best
Dave
